packages:
  - packages/*

verifyDepsBeforeRun: error
enableGlobalVirtualStore: false

allowBuilds:
  dprint: false
  esbuild: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - '@dprint/android-arm64@0.58.0'
  - '@dprint/android-x64@0.58.0'
  - '@dprint/darwin-arm64@0.58.0'
  - '@dprint/darwin-x64@0.58.0'
  - '@dprint/linux-arm64-glibc@0.58.0'
  - '@dprint/linux-arm64-musl@0.58.0'
  - '@dprint/linux-loong64-glibc@0.58.0'
  - '@dprint/linux-loong64-musl@0.58.0'
  - '@dprint/linux-ppc64-glibc@0.58.0'
  - '@dprint/linux-ppc64-musl@0.58.0'
  - '@dprint/linux-riscv64-glibc@0.58.0'
  - '@dprint/linux-x64-glibc@0.58.0'
  - '@dprint/linux-x64-musl@0.58.0'
  - '@dprint/win32-arm64@0.58.0'
  - '@dprint/win32-x64@0.58.0'
  - '@effect/tsgo-darwin-arm64@0.47.0'
  - '@effect/tsgo-darwin-x64@0.47.0'
  - '@effect/tsgo-linux-arm64@0.47.0'
  - '@effect/tsgo-linux-arm@0.47.0'
  - '@effect/tsgo-linux-x64@0.47.0'
  - '@effect/tsgo-win32-arm64@0.47.0'
  - '@effect/tsgo-win32-x64@0.47.0'
  - '@effect/tsgo@0.47.0'
  - dprint@0.58.0
